// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.antherlisten.online.listentogether.proto;

@kotlin.jvm.JvmName("-initializeapproveJoinPayload")
public inline fun approveJoinPayload(block: com.antherlisten.online.listentogether.proto.ApproveJoinPayloadKt.Dsl.() -> kotlin.Unit): com.antherlisten.online.listentogether.proto.Listentogether.ApproveJoinPayload =
  com.antherlisten.online.listentogether.proto.ApproveJoinPayloadKt.Dsl._create(com.antherlisten.online.listentogether.proto.Listentogether.ApproveJoinPayload.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `listentogether.ApproveJoinPayload`
 */
public object ApproveJoinPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.antherlisten.online.listentogether.proto.Listentogether.ApproveJoinPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.antherlisten.online.listentogether.proto.Listentogether.ApproveJoinPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.antherlisten.online.listentogether.proto.Listentogether.ApproveJoinPayload = _builder.build()

    /**
     * `string user_id = 1;`
     */
    public var userId: kotlin.String
      @kotlin.jvm.JvmName("getUserId")
        get() = _builder.userId
      @kotlin.jvm.JvmName("setUserId")
        set(value) {
        _builder.userId = value
      }
    /**
     * `string user_id = 1;`
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.antherlisten.online.listentogether.proto.Listentogether.ApproveJoinPayload.copy(block: `com.antherlisten.online.listentogether.proto`.ApproveJoinPayloadKt.Dsl.() -> kotlin.Unit): com.antherlisten.online.listentogether.proto.Listentogether.ApproveJoinPayload =
  `com.antherlisten.online.listentogether.proto`.ApproveJoinPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

