// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.antherlisten.online.listentogether.proto;

@kotlin.jvm.JvmName("-initializeerrorPayload")
public inline fun errorPayload(block: com.antherlisten.online.listentogether.proto.ErrorPayloadKt.Dsl.() -> kotlin.Unit): com.antherlisten.online.listentogether.proto.Listentogether.ErrorPayload =
  com.antherlisten.online.listentogether.proto.ErrorPayloadKt.Dsl._create(com.antherlisten.online.listentogether.proto.Listentogether.ErrorPayload.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `listentogether.ErrorPayload`
 */
public object ErrorPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.antherlisten.online.listentogether.proto.Listentogether.ErrorPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.antherlisten.online.listentogether.proto.Listentogether.ErrorPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.antherlisten.online.listentogether.proto.Listentogether.ErrorPayload = _builder.build()

    /**
     * `string code = 1;`
     */
    public var code: kotlin.String
      @kotlin.jvm.JvmName("getCode")
        get() = _builder.code
      @kotlin.jvm.JvmName("setCode")
        set(value) {
        _builder.code = value
      }
    /**
     * `string code = 1;`
     */
    public fun clearCode() {
      _builder.clearCode()
    }

    /**
     * `string message = 2;`
     */
    public var message: kotlin.String
      @kotlin.jvm.JvmName("getMessage")
        get() = _builder.message
      @kotlin.jvm.JvmName("setMessage")
        set(value) {
        _builder.message = value
      }
    /**
     * `string message = 2;`
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.antherlisten.online.listentogether.proto.Listentogether.ErrorPayload.copy(block: `com.antherlisten.online.listentogether.proto`.ErrorPayloadKt.Dsl.() -> kotlin.Unit): com.antherlisten.online.listentogether.proto.Listentogether.ErrorPayload =
  `com.antherlisten.online.listentogether.proto`.ErrorPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

